services:
  architects-codex:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: architects-codex-backend
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=development
      - PORT=3030
      - JWT_SECRET=cosmic_horror_secret_key
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/api/game/cosmic-entities"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - cosmic-network

networks:
  cosmic-network:
    driver: bridge