services:
  architects-codex:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: architects-codex-app
    ports:
      - "3030:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - JWT_SECRET=cosmic_horror_secret_key
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - cosmic-network

networks:
  cosmic-network:
    driver: bridge